# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    
volumes:
  database-data:

# database.env
# POSTGRES_USER=unicorn_user
# POSTGRES_PASSWORD=magical_password
# POSTGRES_DB=rainbow_database